"""Alembic's runtime environment.

## This file runs on the DIRECT endpoint, and only ever the direct one
Neon fronts the database with PgBouncer in transaction pooling mode. `app/db.py` explains why the
application wants that; migrations want the opposite. Alembic takes a **connection-scoped advisory
lock** so two deploys cannot migrate at once, and under a transaction pooler "the connection" is
whatever backend the pooler hands out at the start of each transaction — so the lock can be taken on
one backend and released against another, and the mutual exclusion it exists to provide is not
there. DDL against a pooler has the same shape of problem for the same reason.

So this module reads `DATABASE_URL_DIRECT` and **refuses to run without it**. It does not fall back
to `DATABASE_URL`. A fallback would make the wrong endpoint the *easy* one — it would work on a
small schema, in testing, most of the time, and fail during a concurrent deploy against a large
table, which is the least recoverable moment available.

That refusal is the reason `app.config.Settings.database_url_direct` exists but is imported nowhere:
the two URLs are kept reachable from two different places on purpose.
"""

from __future__ import annotations

import asyncio
import os
from logging.config import fileConfig

from alembic import context
from sqlalchemy import pool
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import async_engine_from_config

# Importing the PACKAGE, not the individual modules: `Base.metadata` only contains a table whose
# module has been imported, and autogenerate compares the database against that metadata. A model
# nobody imported does not raise — it shows up as a migration proposing to DROP the table.
from app.models import Base

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata

#: The environment variable holding the direct (non-pooled) endpoint. See the module docstring.
DIRECT_URL_ENV = "DATABASE_URL_DIRECT"


def _direct_url() -> str:
    """Return the direct URL, or fail with an error that says what to set.

    Alembic's own failure mode for a missing URL is a `driver://` placeholder and a message about an
    unknown dialect, which sends the reader looking for a missing package. Cheaper to answer the
    question here.
    """
    url = os.environ.get(DIRECT_URL_ENV)
    if not url:
        raise RuntimeError(
            f"{DIRECT_URL_ENV} is not set. Migrations run against Neon's DIRECT endpoint, "
            f"never the pooled one — Alembic's version lock is connection-scoped and a "
            f"transaction pooler does not preserve it. Set "
            f"{DIRECT_URL_ENV}=postgresql+asyncpg://... (the host WITHOUT '-pooler'). "
            f"See backend/DEPLOY.md."
        )
    return url


def run_migrations_offline() -> None:
    """Emit SQL to stdout instead of running it (`alembic upgrade head --sql`).

    Worth keeping working: it is how a migration gets reviewed as SQL before it is run against
    anything, and how one gets handed to a database that CI has no credentials for.
    """
    context.configure(
        url=_direct_url(),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        # Without this, a change to a column's server default is invisible to autogenerate.
        compare_server_default=True,
    )

    with context.begin_transaction():
        context.run_migrations()


def do_run_migrations(connection: Connection) -> None:
    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        # Type changes are not detected by default — a VARCHAR(64) widened to VARCHAR(128) in the
        # model would silently not appear in an autogenerated revision.
        compare_type=True,
        compare_server_default=True,
    )

    with context.begin_transaction():
        context.run_migrations()


async def run_async_migrations() -> None:
    configuration = config.get_section(config.config_ini_section, {})
    configuration["sqlalchemy.url"] = _direct_url()

    connectable = async_engine_from_config(
        configuration,
        prefix="sqlalchemy.",
        # One connection, used once, closed. `NullPool` here is not the same decision as the one in
        # app/db.py: this process migrates and exits, so a pool would only ever hold a connection
        # open past the point anything needs it.
        poolclass=pool.NullPool,
    )

    async with connectable.connect() as connection:
        await connection.run_sync(do_run_migrations)

    await connectable.dispose()


def run_migrations_online() -> None:
    asyncio.run(run_async_migrations())


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
